### ISSUE TITLE
Documentation changes

### ISSUE THREAD

**Issue by 190n** [blahajjessie/kakaw#30]
for @blahajjessie to fix in a PR

- change `time` field description under `startQuestion` message to: "number of milliseconds until answers stop being accepted"
- add field under `startQuestion` message: "`index` (number): index of the question being started"
- change `answerText` to `answerTexts` under `startQuestion`
- `endQuestion` needs to also include `questionText`, `answerTexts`, and `index`

For other people: We also need some way for the player to learn its own username from the server. Simplest way seems to be adding it as a field under both `startQuestion` and `endQuestion` messages -- we currently repurpose those for "catch a client up if they disconnected for a while" (such has how `startQuestion` includes the player's current score) so it seems to fit decently well. Thoughts?

**Comment by celdond** [comment]
Yeah, I agree it does fit well.  Those two messages are essentially the entire control for the game, so I cannot think of a better place to put such a field.

**Comment by jasminetai** [comment]
I agree; adding the player's own username in startQuestion and endQuestion makes good sense and should hopefully be pretty simple to do.

**Comment by 190n** [comment]
I think we also need a message for the host to know how many players have answered a question so far.

**Comment by 190n** [comment]
^^^ @blahajjessie can you figure that out OR decide to throw it in `startQuestion` lol

At this point should we rename start/endQuestion to, like... I don't know. `questionInProgress` and `postQuestion`? Something like that. Or we can leave them.

**Comment by blahajjessie** [comment]
> ^^^ @blahajjessie can you figure that out OR decide to throw it in `startQuestion` lol
> 
> At this point should we rename start/endQuestion to, like... I don't know. `questionInProgress` and `postQuestion`? Something like that. Or we can leave them.

We can leave the names as is, i think

**Comment by blahajjessie** [comment]
> I think we also need a message for the host to know how many players have answered a question so far.

ill stick this into the documentation

**Comment by blahajjessie** [comment]
fixed in #38
