### ISSUE TITLE
Game persists when host presses "back"

### ISSUE THREAD

**Issue by blahajjessie** [blahajjessie/kakaw#46]
# Original issue
Steps to recreate:
- Create a game
- have a player join
- Press "back" on the host (either the browser back button or the back button in the UI)
- make a new game

Expected Behavior:
- there are no players in the new game
- Eventually, this should send a message to the server telling it to close the game. 

Current behavior:
- Players connected to the old game show up as being connected to the new game
- The number of players remains the same

# Edit
This seems to apply if the host is in any state (ex: mid question)
It might also be a good idea to prevent the browser default back behavior, and force the host to end a game before pressing the back button.

**Comment by 190n** [comment]
fixed on frontend-routing-2 branch
